### ISSUE TITLE
Finish the exercise

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/m2-evaluacion-intermedia-martagrio#1]
Cool job @martagrio  !!!

Here you have some tips to improve the exercise:

### JavaScript

- [ ] Define the logic to make the counter work using a global variable

### HTML

- [ ] Use a `label` to define the content of the input
- [ ] Connect the label to the input using the `for` attribute of the label and the `id` of the input

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting the enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

**Comment by martagrio** [comment]
Thank you for the tips. I made all the improvements recommended in a new branch, review, and once I checked everything works correctly, merged it with the master.

Kind Regards
